stages:
  data_cleaning:
    cmd:  python src\data_cleaning.py
    deps:
      - data\raw\swiggy.csv
      - src\data_cleaning.py
    outs:
      - data\cleaned\swiggy_cleaned.csv
  
 
  data_preparation:
    cmd: python src/data_preparation.py
    params:
      - data_preparation.test_size
      - data_preparation.random_state
    deps:
      - data/cleaned/swiggy_cleaned.csv
      - src/data_preparation.py
    outs:
      - data/interim/train.csv
      - data/interim/test.csv
