stages:
  data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
      - data/raw/swiggy.csv
      - src/data/data_cleaning.py
    outs:
      - data/cleaned/swiggy_cleaned.csv

  data_preparation:
    cmd: python src/data/data_preparation.py
    params:
      - data_preparation.test_size
      - data_preparation.random_state
    deps:
      - data/cleaned/swiggy_cleaned.csv
      - src/data/data_preparation.py
    outs:
      - data/interim/train_data.csv
      - data/interim/test_data.csv

  data_preprocessing:
    cmd: python src/feature_engineering/data_preprocessing.py
    deps:
      - src/feature_engineering/data_preprocessing.py
      - data/interim/train_data.csv
      - data/interim/test_data.csv
    outs:
      - data/processed/x_train_trans.pkl
      - data/processed/y_train.pkl

  model_building:
    cmd: python src/model/model_building.py
    params:
      - model_building.rf_params
      - model_building.lgbm_params
    deps:
      - src/model/model_building.py
      - data/processed/x_train_trans.pkl
      - data/processed/y_train.pkl
    outs:
      - src/model/model.pkl
      - src/model/transformer.pkl
    
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - data/interim/train_data.csv
      - data/interim/test_data.csv
      - src/model/model.pkl
      - data\processed\preprocessor.pkl
    outs:
      - run_information.json

  register_model:
    cmd: python src/model/register_model.py
    deps:
       - src/model/register_model.py
       - run_information.json




