name: CI-CD Pipeline

on: 
  push:

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        lfs: true  # Add this if you use Git LFS

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc[s3]  # Ensure DVC with S3 support is installed
        pip install dagshub

    - name: Configure AWS credentials
      run: echo "AWS credentials will be passed via env."
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2

    - name: Debug AWS credentials (temp)
      run: |
        echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}"
        echo "SECRET length: ${#AWS_SECRET_ACCESS_KEY}"
        aws --version || echo "awscli not installed"
        aws sts get-caller-identity || echo "Credentials invalid or STS disabled"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2

    - name: Pull DVC-tracked data
      run: dvc pull
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2

    - name: Run DVC Pipeline
      run: dvc repro

    - name: Push DVC-tracked data to remote
      run: dvc push
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add changes to Git
      run: git add .

    - name: Commit changes
      if: ${{ github.actor != 'github-actions[bot]' }}
      run: |
        git commit -m "Automated commit of DVC outputs and updated code" || echo "No changes to commit"

    - name: Push changes
      if: ${{ github.actor != 'github-actions[bot]' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin ${{ github.ref_name }}
